{
    "_comment": "File Search Configuration Schema - Generated by BMAD",
    "version": "1.0.0",
    "search": {
        "case_sensitive": false,
        "include_hidden": false,
        "max_results": 10000,
        "file_extensions_to_exclude": [],
    },
    "ui": {
        "window_width": 800,
        "window_height": 600,
        "results_font_size": 12,
        "show_file_icons": true,
        "auto_expand_results": false,
    },
    "highlighting": {
        "enabled": true,
        "color": "#FFFF99",
        "case_sensitive": false,
        "style": "background",
    },
    "performance": {
        "search_thread_count": 4,
        "enable_search_cache": false,
        "cache_ttl_minutes": 30,
    },
    "plugins": {"enabled": []},
}
